# Generated by Django 5.1.1 on 2024-11-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=50)),
                ('competition_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_stadium', models.TextField()),
                ('team_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(verbose_name='Datum utakmice')),
                ('match_stadium', models.TextField()),
                ('match_score1', models.IntegerField()),
                ('match_score2', models.IntegerField()),
                ('match_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.competition')),
                ('match_team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.team')),
                ('match_team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.team')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_teams',
            field=models.ManyToManyField(to='main.team'),
        ),
    ]
